### ISSUE TITLE
Installation fails on 4.0.4 (TypeError: cannot unpack non-iterable UserVar object)

### ISSUE THREAD

**Issue by vbr-cts** [SeisoLLC/zeek-kafka#29]
# Summary of the issue

The plugin fails to install on zeek 4.0.4, throwing the following error:

```
TypeError: cannot unpack non-iterable UserVar object
```

## Expected behavior

The plugin installs properly with zkg

## Steps to reproduce

```
cd /usr/src/zeek-${ZEEK_VERSION}/ && ./configure --with-pcap=/usr/local --prefix=/opt/zeek && make -j4 && make install
zkg autoconfig --force
zkg install seisollc/zeek-kafka --version v1.0.0 --force
```

## Logs, errors, etc.

```
# zkg install seisollc/zeek-kafka --version v1.0.0 --force
Traceback (most recent call last):
  File "/opt/zeek/bin/zkg", line 2511, in <module>
    main()
  File "/opt/zeek/bin/zkg", line 2508, in main
    args.run_cmd(manager, args, config, configfile)
  File "/opt/zeek/bin/zkg", line 603, in cmd_install
    [info for info, _, _ in package_infos])
  File "/opt/zeek/bin/zkg", line 120, in prompt_for_user_vars
    for key, value, desc in requested_user_vars:
TypeError: cannot unpack non-iterable UserVar object
```

## Your environment

* Zeek 4.0.4 (LTS)
* 1.0.0
* Debian stable

**Comment by JonZeolla** [comment]
As of 9c160d81b04373454494b3bcfe5170c9f741d759 we updated Zeek to 4.0.5 and it's running our end tests without issue.  Are you still having a problem?

**Comment by JonZeolla** [comment]
@vbr-cts are you still having an issue?

**Comment by JonZeolla** [comment]
Closing this issue due to inactivity

**Comment by vbr-cts** [comment]
Upgrading to zeek 4.2 solved the problem for me
